# Generated by Django 4.1.2 on 2022-10-13 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_forminput_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='forminput',
            name='ageranges',
            field=models.CharField(default=-1, max_length=4),
        ),
        migrations.AddField(
            model_name='forminput',
            name='audiences',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='forminput',
            name='gp',
            field=models.CharField(default=-1, max_length=60),
        ),
        migrations.AddField(
            model_name='forminput',
            name='recommendations',
            field=models.CharField(default=-1, max_length=600),
        ),
    ]
