# Generated by Django 4.1.2 on 2022-10-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_forminput_ageranges_forminput_audiences_forminput_gp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='singleforminput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('age', models.IntegerField(default=1)),
                ('sum', models.IntegerField(default=0)),
                ('gp', models.CharField(default=-1, max_length=60)),
                ('recommendations', models.CharField(default=-1, max_length=600)),
            ],
        ),
    ]
